#!/usr/bin/env bash
if (( "$#" < 3 )); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 0
else
    src="$1"
    serverIp="$2"
    username="$3"
    identity_file="$4"
    if (( "$#" == 3 )); then
        scp -o StrictHostKeyChecking=no "$src" "${username}@${serverIp}:~/"
    else
        scp -o StrictHostKeyChecking=no -i "$identity_file" "$src" "${username}@${serverIp}:~/"
    fi
fi
