#!/usr/bin/env bash
# This script configures a new nginx server on a new linux machine
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow ssh
echo y | ufw enable
ufw reload
echo "Hello World!" > /var/www/html/index.html
service nginx restart
