#!/usr/bin/env bash
# This script configures an nginx server on a new server with a 301 redirect on path /redirect_me
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo y | ufw enable
ufw reload
sed -i '47 a \\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
service nginx restart
