#!/usr/bin/env bash
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo y | ufw enable
ufw reload
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '47 a \\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
sed -i '51 a \\terror_page 404 \/404.html;\n' /etc/nginx/sites-available/default
service nginx restart
