#!/usr/bin/env bash
# This script configures an nginx server on a new server with a 301 redirect on path /redirect_me
apt-get update
apt-get -y install nginx
bash -c "echo 'Hello World!' > /var/www/html/index.html"
bash -c "echo 'Ceci n\'est pas une page' > /var/www/html/404.html"
sed -i '60 a \\tadd_header X-Served-By "\$hostname";\n' /etc/nginx/nginx.conf
sed -i '47 a \\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
sed -i '51 a \\terror_page 404 \/404.html;\n' /etc/nginx/sites-available/default
service nginx restart
