#!/usr/bin/env bash
# This script pings an ip address passed as an argument five times

if [[ -z "${1}" ]]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi

