#!/usr/bin/env bash
# This fixes nginx configuration to listen on port 80 on all ipv4 addresses
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=[[:alpha:]]*\;/\;/' /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx restart
