#!/usr/bin/env bash
# Rogue script

file=/var/run/myscript.pid

echo "$$" > "$file"
trap "echo 'Y U no love me?!'" SIGINT
trap "echo I hate the kill command; rm -f '$file'; exit" SIGTERM
trap "rm -f '$file'; exit" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
