#!/usr/bin/env bash
# This is a bash init script that manages manage_my_process script

file=/var/run/my_process.pid

if [[ "${1}" == "start" ]]
then
    ./manage_my_process &
    echo "$!" > "$file"
    echo "manage_my_process started"
elif [[ "${1}" == "stop" ]]
then
    kill "$(cat ${file})" && rm -f "$file"
    echo "manage_my_process stopped"
elif [[ "${1}" == "restart" ]]
then
    kill "$(cat ${file})" && rm -f "$file"
    ./manage_my_process &
    echo "$!" > "$file"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

