#!/usr/bin/env bash
# A script that  script that runs indefinitely and writes 'I am alive!' to the file '/tmp/my_process'

file="/tmp/my_process"
while true
do
    echo "I am alive!" >> "$file"
    sleep 2
done 
