#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# The script only displays:
# username
# user id
# Home directory path for the user

file=/etc/passwd

while read -r usrs
do
    echo "$usrs" | cut -d ':' -f 1,3,6
done < "$file"
