#!/usr/bin/env bash
# This script is displays "Best School" 10 times
# On the 9th iteration, Hi is also printed
i=1
while [ $i -le 10 ]
do
	echo 'Best School'
	if [ $i -eq 9 ]
	then
		echo 'Hi'
	fi
	(( ++i ))
done
