#!/usr/bin/env bash
# This script is displays "Best School" 10 times
# On the 9th iteration, Hi is also printed
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo 'bad luck'
	elif [ $i -eq 8 ]
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	(( ++i ))
done
