#!/usr/bin/env bash
# This script is displays "Best School" 10 times
# On the 9th iteration, Hi is also printed
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo 'bad luck from China'
			;;
		9)
			echo 'bad luck from Japan'
			;;
		17)
			echo 'bad luck from Italy'
			;;
	esac
	(( ++i ))
done
