#!/usr/bin/env bash
# This bash script configures a firewall to only allow traffic on tcp ports 22, 80 and 443
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw reload
