#!/usr/bin/env bash
# This script fixes a bug on a particular server
pkill -9 apache
sed -i '21,22s/80/8080/' /etc/nginx/sites-available/default
chmod a+r /etc/nginx/nginx.conf
sudo -u nginx service nginx start
